import os

PORT = 5000
DASHSCOPE_API_KEY = "sk-6a083d4e3eee4a898269d9a68fda25fd"
METASO_API_KEY = "mk-C997D74C2BCE37E86A38BF460B6A58E3"
MYSQL_HOST = os.environ.get("MYSQL_HOST", "127.0.0.1")
MYSQL_PORT = int(os.environ.get("MYSQL_PORT", "3306"))
MYSQL_USER = os.environ.get("MYSQL_USER", "root")
MYSQL_PASSWORD = os.environ.get("MYSQL_PASSWORD", "")
MYSQL_DATABASE = os.environ.get("MYSQL_DATABASE", "llmrag")
MYSQL_CHARSET = os.environ.get("MYSQL_CHARSET", "utf8mb4")
MYSQL_POOL_SIZE = int(os.environ.get("MYSQL_POOL_SIZE", "5"))
MYSQL_POOL_RECYCLE = int(os.environ.get("MYSQL_POOL_RECYCLE", "3600"))
UPLOAD_ALLOWED_EXTENSIONS = ["txt", "pdf", "docx", "doc"]
UPLOAD_MAX_CONTENT_LENGTH = 20 * 1024 * 1024
CONVERSATION_INDEX_CHUNK_SIZE = 700
CONVERSATION_INDEX_CHUNK_OVERLAP = 120

